# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mana
tagline:          'A Jekyll theme'
description:      'Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              manafount.github.io/
baseurl:          /

author:
  name:           'Matt Kerchner'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars

github:
  repo:           https://github.com/manafount/
